"""empty message

Revision ID: c3622af78e44
Revises: 9cd118332675
Create Date: 2024-02-01 22:06:05.251730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3622af78e44'
down_revision = '9cd118332675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patientinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('job', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('emergencyContact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('createDate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updateDate', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['mobile'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patientinfo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updateDate')
        batch_op.drop_column('createDate')
        batch_op.drop_column('emergencyContact')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('nation')
        batch_op.drop_column('job')
        batch_op.drop_column('address')
        batch_op.drop_column('mobile')

    # ### end Alembic commands ###
