"""empty message

Revision ID: c70ce7c3b20b
Revises: c3622af78e44
Create Date: 2024-03-17 21:09:57.890040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c70ce7c3b20b'
down_revision = 'c3622af78e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet1B',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('chronicDisease', sa.Integer(), nullable=True),
    sa.Column('medicationNames', sa.String(length=100), nullable=True),
    sa.Column('medicationDuration', sa.Integer(), nullable=True),
    sa.Column('recentInfectionStatus', sa.Integer(), nullable=True),
    sa.Column('recentJointSurgery', sa.Boolean(), nullable=True),
    sa.Column('cardiovascularFamilyHistory', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet2A',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('height', sa.Double(), nullable=True),
    sa.Column('weight', sa.Double(), nullable=True),
    sa.Column('waistline', sa.Double(), nullable=True),
    sa.Column('restingHeartRate', sa.Integer(), nullable=True),
    sa.Column('sbp', sa.Integer(), nullable=True),
    sa.Column('dbp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet2B',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('tc', sa.Double(), nullable=True),
    sa.Column('tg', sa.Double(), nullable=True),
    sa.Column('ldl', sa.Double(), nullable=True),
    sa.Column('hdl', sa.Double(), nullable=True),
    sa.Column('fpg', sa.Double(), nullable=True),
    sa.Column('hba1c', sa.Double(), nullable=True),
    sa.Column('scr', sa.Double(), nullable=True),
    sa.Column('alb', sa.Double(), nullable=True),
    sa.Column('ast', sa.Double(), nullable=True),
    sa.Column('alt', sa.Double(), nullable=True),
    sa.Column('sua', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet2C',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('leftlmt', sa.Double(), nullable=True),
    sa.Column('rightlmt', sa.Double(), nullable=True),
    sa.Column('carotidAtheroscleroticPlaque', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet2D',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('lestAbi', sa.Double(), nullable=True),
    sa.Column('rightAbi', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet2E',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('lfap', sa.Double(), nullable=True),
    sa.Column('lsm', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet3',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('crfTestType', sa.String(length=100), nullable=True),
    sa.Column('vo2Max', sa.Double(), nullable=True),
    sa.Column('dhgs', sa.Double(), nullable=True),
    sa.Column('sitUpTest5', sa.Integer(), nullable=True),
    sa.Column('balanceTest30', sa.String(length=100), nullable=True),
    sa.Column('balanceTest60', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet4',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('object', sa.String(length=100), nullable=False),
    sa.Column('restingHeartRate', sa.Integer(), nullable=True),
    sa.Column('comorbidities', sa.String(length=100), nullable=True),
    sa.Column('aerobicExerciseType', sa.String(length=100), nullable=False),
    sa.Column('resistanceExerciseType', sa.String(length=100), nullable=True),
    sa.Column('coreMusclesInvolved', sa.String(length=100), nullable=True),
    sa.Column('preparationNote', sa.String(length=100), nullable=True),
    sa.Column('antidiabeticDrugNote', sa.String(length=100), nullable=True),
    sa.Column('dietNote', sa.String(length=100), nullable=True),
    sa.Column('unexpectedEventsNote', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet4B',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('startTime', sa.TIMESTAMP(), nullable=False),
    sa.Column('endTime', sa.TIMESTAMP(), nullable=False),
    sa.Column('warmUpType', sa.String(length=100), nullable=False),
    sa.Column('warmUpDuration', sa.Integer(), nullable=False),
    sa.Column('heartRateLowerLimit', sa.Integer(), nullable=False),
    sa.Column('heartRateUpperLimit', sa.Integer(), nullable=False),
    sa.Column('exerciseDuration', sa.Integer(), nullable=False),
    sa.Column('exerciseFrequency', sa.Integer(), nullable=False),
    sa.Column('coolingDownType', sa.String(length=100), nullable=False),
    sa.Column('coolingDownDuration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet4C',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('startTime', sa.TIMESTAMP(), nullable=False),
    sa.Column('endTime', sa.TIMESTAMP(), nullable=False),
    sa.Column('warmUpType', sa.String(length=100), nullable=False),
    sa.Column('warmUpDuration', sa.Integer(), nullable=False),
    sa.Column('exercises', sa.String(length=100), nullable=False),
    sa.Column('intensity', sa.String(length=100), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('groupNumber', sa.Integer(), nullable=False),
    sa.Column('restTime', sa.Integer(), nullable=False),
    sa.Column('exerciseFrequency', sa.Integer(), nullable=False),
    sa.Column('coolingDownType', sa.String(length=100), nullable=False),
    sa.Column('coolingDownDuration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patientinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('idNumber', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('marital', sa.Boolean(), nullable=True))
        batch_op.drop_column('username')
        batch_op.drop_column('marital_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patientinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marital_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('marital')
        batch_op.drop_column('idNumber')
        batch_op.drop_column('name')

    op.drop_table('sheet4C')
    op.drop_table('sheet4B')
    op.drop_table('sheet4')
    op.drop_table('sheet3')
    op.drop_table('sheet2E')
    op.drop_table('sheet2D')
    op.drop_table('sheet2C')
    op.drop_table('sheet2B')
    op.drop_table('sheet2A')
    op.drop_table('sheet1B')
    # ### end Alembic commands ###
